# Ruby Gemfile for TraceOrigin testing
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

# Core gems
gem "rails", "~> 7.0.0"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

# Authorization
gem "devise", "~> 4.8"
gem "pundit", "~> 2.2"

# Testing
group :test do
  gem "rspec-rails", "~> 5.1"
  gem "factory_bot_rails", "~> 6.2"
end

# Development
group :development do
  gem "pry-rails", "~> 0.3"
  gem "rubocop", "~> 1.31"
end
